CREATE TABLE IF NOT EXISTS users
(
    id            INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    login         TEXT      NOT NULL UNIQUE,
    password      TEXT      NOT NULL,
    registered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders
(
    id           INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    order_id     TEXT      NOT NULL UNIQUE,
    user_id      INTEGER   NOT NULL REFERENCES users (id),
    status TEXT      NOT NULL DEFAULT 'REGISTERED' CHECK (status IN ('REGISTERED', 'INVALID', 'PROCESSING', 'PROCESSED')),
    accrual      INTEGER,
    uploaded_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
