name: gophermart

services:
  accrual:
    build:
      context: ../../cmd/accrual
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gophermart
    volumes:
      - db_storage:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
      interval: 5s
      timeout: 5s
      retries: 10

  mock-server:
    image: mockserver/mockserver:mockserver-5.15.0
    ports:
      - "8080:1080"
    environment:
      MOCKSERVER_LOG_LEVEL: DEBUG
      MOCKSERVER_MAX_EXPECTATIONS: 100
      MOCKSERVER_MAX_HEADER_SIZE: 8192
      MOCKSERVER_WATCH_INITIALIZATION_JSON: true
      MOCKSERVER_INITIALIZATION_JSON_PATH: /opt/mockserver/*.json
    volumes:
      - ./config/mockserver:/opt/mockserver

volumes:
  db_storage: